test: fixes err status masked by 1cf9a9c6ff
Was causing unexpected continued execution of script:
```sh
$ make test
... snipped ...
[21] "test-multi-equation"      asserting target's behavior     /media/terrahome/jzacsh-tmp/src/PLT2016Spring/src/tests/test-multi-equation.c: In function ‘find_SomeContext_0’:
/media/terrahome/jzacsh-tmp/src/PLT2016Spring/src/tests/test-multi-equation.c:6:5: error: expected expression before ‘if’
 a = if (3. > 4.)
     ^
        Result: FAIL
1c1
< 4
---
> ./bin//e2e-tests.sh: line 228: /media/terrahome/jzacsh-tmp/src/PLT2016Spring/src/tests/test-multi-equation.a: No such file or directory
```