start with broken test of find expressions
Example test-run, as of this commit:
```bash
$ make test
 # snipped
  test-find.eq...FAILED
    ./microc.native failed on ./microc.native < tests/test-find.eq > test-find.eq.ll
  ###### Testing test-find.eq
  ./microc.native < tests/test-find.eq > test-find.eq.ll
  Fatal error: exception Failure("unrecognized function main")
  ###### FAILED

  test-gcd.eq...FAILED
    ./microc.native failed on ./microc.native < tests/test-gcd.eq > test-gcd.eq.ll
  ###### Testing test-gcd.eq
  ./microc.native < tests/test-gcd.eq > test-gcd.eq.ll
  Fatal error: exception Parsing.Parse_error
  ###### FAILED

  Makefile:16: recipe for target 'test' failed
  make: *** [test] Error 1
```